#!/bin/sh

#chmod +x ant
#chmod +x scripts/history.sh
#chmod +x scripts/team.sh

DIR="$(cd "$(dirname "$0")" && pwd)"

export ANT_HOME="$DIR/apache-ant"
export PATH="$ANT_HOME/bin:$PATH"

export ANT_OPTS="-Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 $ANT_OPTS"


exec "$ANT_HOME/bin/ant" "$@"